name: MI-SPORT-TASK

on:
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发 (UTC时区 H+8)
    - cron: "10 9 * * *"


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # 设置服务器时区为东八区
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    
    - name: Use Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    #运行
    - name: Run app
      env:
          XIAOMI_USERNAME: ${{secrets.XIAOMI_USERNAME}}
          XIAOMI_PASSWORD: ${{secrets.XIAOMI_PASSWORD}}
          XIAOMI_STEP_RANG: ${{secrets.XIAOMI_STEP_RANG}}
      run: go run main.go
